url: ''
baseurl: ''
title: 'bobbymeyer.com'

plugins:
  - jekyll-postcss
  - jekyll-paginate-v2

postcss:
  cache: false

exclude:
  - package.json
  - postcss.config.js
  - tailwind.config.js
  - yarn.lock

pagination:
  enabled: true
  debug: false
  per_page: 6
  sort_reverse: true
  title: ':title - page :num'
  trail:
    before: 2
    after: 2
  permalink: '/page/:num/'

# Conversion

markdown: kramdown
highlighter: rouge
